#!/usr/bin/env python

# chipmusic-convert
# Convert chiptune tracker formats to wav/ogg/flac conveniently

import sys
import getopt

def main():
    arg_config, sources = parse_arguments()

    print("chipmusic-convert")
    print("recursive = ", arg_config['recursive'])
    

# returns
# 1. a dictionary with commandline argument settings
# 2. the remaining non-option arguments
def parse_arguments():
    arg_config = {}

    help_text="""chipmusic-convert - convert chip music formats to wav/ogg/flac

Synopsis:
  chipmusic-convert [options] source ...

'source' is either a single file one of the supported formats or a
directory with files to be converted. After the options, any number of
source files and directories can be given.

Options:
  -r, --recursive:
    Descend into subfolders for all folder sources.
"""
    
    # set default option values
    arg_config['recursive'] = False
    
    # parse command line options
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hr", ["help", "recursive"])
    except getopt.error as msg:
        print(msg)
        print("for help use --help")
        sys.exit(1)

    # process options
    for option, value in opts:
        if option in ("-h", "--help"):
            print(help_text)
            sys.exit(0)
        if option in ("-r", "--recursive"):
            arg_config['recursive'] = True
            
    # process arguments
    # for arg in args:
    #     process(arg) # process() is defined elsewhere

    return arg_config, args
    
        
if __name__ == "__main__":
    main()
